export const fields = [
  {
    id: 99,
    label: '您的姓名',
    model: 'name',
    type: 'input',
    required: true,
  },
  {
    id: 100,
    label: '您的性别',
    model: 'gender',
    type: 'select',
    required: true,
    options: ['男', '女'],
  },
  {
    id: 1,
    label: '您的年龄',
    model: 'age',
    type: 'radio',
    required: true,
    options: [
      { value: '18-25岁', label: '18-25岁' },
      { value: '26-35岁', label: '26-35岁' },
      { value: '36-45岁', label: '36-45岁' },
      { value: '46岁以上', label: '46岁以上' },
    ],
  },
  {
    id: 101,
    label: '您的电话号码',
    model: 'phone',
    type: 'input',
    required: true,
  },
  {
    id: 102,
    label: '请选择您的置业顾问',
    model: 'advisor',
    type: 'select',
    required: true,
    options: [
      '王浩禹', '张程艺', '黄微', '黄廷戈', '周丹', '任昱霏',
      '邓梦池', '范迅妤', '黄琴', '王博', '夏天', '林二',
      '何水生', '钱可可', '郭维', '高向南', '李强', '彭叶玲',
      '叶瞳萱', '吴迪', '范昕蕾', '饶云博',
    ],
  },
  {
    id: 3,
    label: '请问您居住的区域是（单选）',
    model: 'livingArea',
    type: 'select',
    required: true,
    options: [
      '青羊中坝', '青羊蔡桥', '青羊万家湾', '青羊成飞', '青羊外金沙', '青羊其他',
      '武侯悦湖', '武侯西部智谷', '武侯机投', '武侯新城南', '武侯双楠', '武侯其他',
      '金牛区其他', '金牛国宾', '锦江区', '高新南区', '温江区', '郫都区',
      '双流区', '成华区', '天府新区', '成都市其他县市区', '四川二级城市', '省外',
    ],
  },
  {
    id: 4,
    label: '请问您的工作区域是（单选）',
    model: 'workArea',
    type: 'select',
    required: true,
    options: [
      '青羊中坝', '青羊蔡桥', '青羊万家湾', '青羊成飞', '青羊外金沙', '青羊其他',
      '武侯悦湖', '武侯西部智谷', '武侯机投', '武侯新城南', '武侯双楠', '武侯其他',
      '金牛区其他', '金牛国宾', '锦江区', '高新南区', '温江区', '郫都区',
      '双流区', '成华区', '天府新区', '成都市其他县市区', '四川二级城市', '省外',
    ],
  },
  {
    id: 5,
    label: '请问您的所属行业是（单选）',
    model: 'industry',
    type: 'select',
    required: true,
    options: [
      '政府机关', '科技类', '信息服务业', '事业单位', '传媒/广告',
      '教育/培训', 'it互联网', '外贸业', '医疗卫生/医药', '金融投资业',
      '房产/建筑业', '自由职业', '退休人员', '其他',
    ],
  },
  {
    id: 6,
    label: '请问您的职业是（单选）',
    model: 'occupation',
    type: 'select',
    required: true,
    options: [
      '企/事业单位', '私营企业主', '企业中高管', '白领上班族',
      '自由职业者', '退休人员', '其他',
    ],
  },
  {
    id: 7,
    label: '请问您目前居住的户型面积是（单选）',
    model: 'floorArea',
    type: 'select',
    required: true,
    options: [
      '70㎡以下', '70-90㎡', '90-100㎡', '110-120㎡',
      '120-130㎡', '130-140㎡', '140㎡以上',
    ],
  },
  {
    id: 9,
    label: '请问您的意向户型面积是（单选）',
    model: 'preferredArea',
    type: 'select',
    required: true,
    options: ['100-120㎡', '120-130㎡', '130-140㎡'],
  },
  {
    id: 13,
    label: '请问您的购房资金是（单选）',
    model: 'purchaseFunds',
    type: 'select',
    required: true,
    options: ['现金', '理财', '卖房置换'],
  },
  {
    id: 11,
    label: '请问您的意向户型结构是（多选）',
    model: 'unitLayoutPreference',
    type: 'checkbox',
    required: true,
    options: [
      { value: '三房双卫', label: '三房双卫' },
      { value: '四房双卫', label: '四房双卫' },
      { value: '四房三卫', label: '四房三卫' },
      { value: '其他', label: '其他' },
    ],
  },
  {
    id: 14,
    label: '请问您的置业次数是（单选）',
    model: 'propertyPurchaseCount',
    type: 'select',
    required: true,
    options: ['首次', '二次', '三次', '四次及以上'],
  },
  {
    id: 15,
    label: '请问您对晓棠的认可点是（多选）',
    model: 'accreditationMetrics',
    type: 'checkbox',
    required: true,
    options: [
      { value: '区域位置', label: '区域位置' },
      { value: '交通配套', label: '交通配套' },
      { value: '教育资源', label: '教育资源' },
      { value: '自然资源', label: '自然资源' },
      { value: '商业配套', label: '商业配套' },
      { value: '金茂品牌', label: '金茂品牌' },
      { value: '物业服务', label: '物业服务' },
      { value: '户型设计', label: '户型设计' },
      { value: '景观打造', label: '景观打造' },
      { value: '会所配套', label: '会所配套' },
      { value: '建筑外立面', label: '建筑外立面' },
      { value: '收纳空间', label: '收纳空间' },
      { value: '未来规划', label: '未来规划' },
      { value: '价格', label: '价格' },
      { value: '社交圈层', label: '社交圈层' },
      { value: '城市界面', label: '城市界面' },
      { value: '交付时间', label: '交付时间' },
      { value: '短期内资金计划', label: '短期内资金计划' },
      { value: '其他', label: '其他' },
    ],
  },
  {
    id: 18,
    label: '请问您关注哪些项目？（多选）',
    model: 'trackedItems',
    type: 'checkbox',
    required: true,
    options: [
      { type: 'group', label: '新房：', value: 'group-new' },
      { label: '华润青羊观宸', value: '华润青羊观宸' },
      { label: '华润青羊润璟', value: '华润青羊润璟' },
      { label: '中粮青云府', value: '中粮青云府' },
      { label: '武侯西派御府', value: '武侯西派御府' },
      { label: '建发源起金沙', value: '建发源起金沙' },
      { label: '新希望机投项目', value: '新希望机投项目' },
      { label: '保利金沙天耀', value: '保利金沙天耀' },
      { label: '复地崑玉锦城', value: '复地崑玉锦城' },
      { label: '成华区同总价段产品', value: '成华区同总价段产品' },
      { label: '东城金茂晓棠', value: '东城金茂晓棠' },
      { label: '其他', value: '新房-其他' },
      { label: '无关注', value: '新房-无关注' },
      { type: 'group', label: '二手房：', value: 'group-used' },
      { label: '蔡桥板块二手', value: '蔡桥板块二手' },
      { label: '中坝板块二手', value: '中坝板块二手' },
      { label: '悦湖板块二手', value: '悦湖板块二手' },
      { label: '万家湾板块二手', value: '万家湾板块二手' },
      { label: '成华区二手房', value: '成华区二手房' },
      { label: '锦江区区二手房', value: '锦江区区二手房' },
      { label: '无关注', value: '二手房-无关注' },
      { label: '其他', value: '二手房-其他' },
    ],
  },
  {
    id: 19,
    label: '请问您是否了解城西CID产城更新规划（单选）',
    model: 'masterPlanReview',
    type: 'select',
    required: true,
    options: ['非常了解', '听说过', '不太了解'],
  },
  {
    id: 20,
    label: '请问您是否了解西川一校三区的布局（单选）',
    model: 'xichuanCampusLayout',
    type: 'select',
    required: true,
    options: ['非常了解', '听说过', '不太了解'],
  },
  {
    id: 21,
    label: '请问您是否了解西川师资情况（单选）',
    model: 'xichuanFaculty',
    type: 'select',
    required: true,
    options: ['非常了解', '听说过', '不太了解'],
  },
  {
    id: 22,
    label: '请问您对于参与以下哪些活动感兴趣？（多选）',
    model: 'eventInterest',
    type: 'checkbox',
    required: true,
    options: [
      { value: '咖啡/品茗', label: '咖啡/品茗' },
      { value: '室内多元化运动', label: '室内多元化运动' },
      { value: '宠物社交', label: '宠物社交' },
      { value: '草坪露营', label: '草坪露营' },
      { value: '草坪观影', label: '草坪观影' },
      { value: '潮流音乐节', label: '潮流音乐节' },
      { value: '亲子运动', label: '亲子运动' },
      { value: '儿童多元化活动', label: '儿童多元化活动' },
      { value: '手作沙龙体验课', label: '手作沙龙体验课' },
      { value: '育儿知识沙龙', label: '育儿知识沙龙' },
      { value: '中医生养课堂', label: '中医生养课堂' },
    ],
  },
  {
    id: 23,
    label: '请问您对于城西金茂晓棠项目有什么建议（必填）',
    model: 'customerInterests',
    type: 'textarea',
    required: true,
    placeholder: '请填写您的建议',
  },
]
